### ISSUE TITLE
Hey Patrick, I needed help on this one.

### ISSUE THREAD

**Issue by lopeselio** [PatrickAlphaC/dungeons-and-dragons-nft#3]
Running
`truffle migrate --reset --network rinkeby`

Compiling your contracts...
===========================
> Compiling ./contracts/DungeonsAndDragonsCharacter.sol
> Compiling ./contracts/Migrations.sol
> Compiling @chainlink/contracts/src/v0.6/VRFConsumerBase.sol
> Compiling @chainlink/contracts/src/v0.6/VRFRequestIDBase.sol
> Compiling @chainlink/contracts/src/v0.6/interfaces/LinkTokenInterface.sol
> Compiling @chainlink/contracts/src/v0.6/vendor/SafeMath.sol
> Compiling @openzeppelin/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/token/ERC721/ERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Enumerable.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Metadata.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/EnumerableMap.sol
> Compiling @openzeppelin/contracts/utils/EnumerableSet.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
> Compilation warnings encountered:

    /home/lion/Desktop/blockchain/nft/dungeons-and-dragons-nft/contracts/DungeonsAndDragonsCharacter.sol:162:5: Warning: Function state mutability can be restricted to pure
    function sqrt(uint256 x) internal view returns (uint256 y) {
    ^ (Relevant source part starts here and spans across multiple lines).

> Artifacts written to /home/lion/Desktop/blockchain/nft/dungeons-and-dragons-nft/build/contracts
> Compiled successfully using:
   - solc: 0.6.6+commit.6c089d02.Emscripten.clang

> Duplicate contract names found for SafeMath.
> This can cause errors and unknown behavior. Please rename one of your contracts.
Error: Unknown arguments format passed to new HDWalletProvider. Please check your configuration and try again
    at Object.exports.getOptions (/home/lion/Desktop/blockchain/nft/dungeons-and-dragons-nft/node_modules/@truffle/hdwallet-provider/src/constructor/getOptions.ts:141:11)
    at new HDWalletProvider (/home/lion/Desktop/blockchain/nft/dungeons-and-dragons-nft/node_modules/@truffle/hdwallet-provider/src/index.ts:53:9)
    at Object.provider (/home/lion/Desktop/blockchain/nft/dungeons-and-dragons-nft/truffle-config.js:7:16)
    at Object.getProvider (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:20:1)
    at Object.create (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:13:1)
    at TruffleConfig.get [as provider] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/configDefaults.js:204:1)
    at Object.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/environment/environment.js:19:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:205:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.1.67 (core: 5.1.67)
Node v15.5.0

**Comment by lopeselio** [comment]
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 10000000 (0x989680)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- insufficient funds for gas * price + value.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:262:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:227:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.1.67 (core: 5.1.67)
Node v15.5.0

**Comment by PatrickAlphaC** [comment]
Do you have any testnet rinkeby in your wallet? It looks like you're getting gas errors.

**Comment by lopeselio** [comment]
Yes I am having gas errors. I tried obtaining test ether 
![image](https://user-images.githubusercontent.com/43913734/109411612-62542080-79c9-11eb-8eb5-dfd0e3cf7bb7.png)

I am using a new wallet, and I am new to this space

**Comment by lopeselio** [comment]
Is there a better way to obtain testnet rinkeby in my wallet ?

**Comment by lopeselio** [comment]
It takes a really long time actually to obtain test ether tokens in rinkeby faucet. Can I try doing this with Ropsten or Kovan test network?

**Comment by PatrickAlphaC** [comment]
You should be able to get testnet ETH quickly. Kovan might be faster.

https://www.youtube.com/watch?v=4ZgFijd02Jo

Maybe this video would help? I would recommend kovan or rinkeby over ropsten though.

**Comment by GoldenRatio3** [comment]
For anyone else who needs to change the testnet it's relatively straightforward by 
- Updating the `2_mycontact_migration` file
- Add the `HDWalletProvider` to the `truffle-config`

`Kovan` testnet does not appear to be supported by opensea for the NFT display
`Ropsten` testnet does not appear to be supported by chainlink for the random number generation
